#!/bin/sh

# Example for $XDG_CONFIG_HOME/nsxiv/exec/image-info
# Called by nsxiv(1) whenever an image gets loaded.
# The output is displayed in nsxiv's status bar.
# Arguments:
#   $1: path to image file (as provided by the user)
#   $2: image width
#   $3: image height
#   $4: fully resolved path to the image file

exec 2>/dev/null
size=$(du -Hh -- "$1" | cut -f 1)
#printf -- '%s [%s] %s' "${4##*/}" "${2}x${3}" "$size"
printf -- '%s [%s] %s' "${4}" "${2}x${3}" "$size"
